---
- hosts: servers
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
      
    - name: install docker-py
      pip: name=docker-py

    - name: log into docker hub registry
      docker_login:
        email: "sikandar.iqbal@zigron.com"
        username: "sikandariqbal94"
        password: "imsikandar007@!#"

    - name: ensure a container is running
      docker_container:
        name: my_container
        state: started
        image: "rawmind/web-test:latest"
        pull: true
        ports:
          - "9001:8080"